model_list:
  - model_name: gemini-pro
    litellm_params:
      model: gemini/gemini-pro
      api_key: os.environ/GEMINI_API_KEY
      fallbacks: [gpt-3.5-turbo-16k]

  - model_name: gemini-pro
    litellm_params:
      model: gemini/gemini-pro
      api_key: os.environ/GEMINI_API_KEY_FALLBACK
      fallbacks: [gpt-3.5-turbo-16k]

  - model_name: gpt-3.5-turbo-16k
    litellm_params:
      model: gpt-3.5-turbo-16k
      api_key: os.environ/OPENAI_API_KEY
      fallbacks: [command-nightly]

  - model_name: command-nightly
    litellm_params:
      model: command
      api_key: os.environ/COHERE_API_KEY
      fallbacks: [openrouter-auto]

  - model_name: command-nightly
    litellm_params:
      model: command
      api_key: os.environ/COHERE_API_KEY_FALLBACK
      fallbacks: [openrouter-auto]

  - model_name: openrouter-auto
    litellm_params:
      model: openrouter/auto
      api_key: os.environ/OPENROUTER_API_KEY

  - model_name: gemini-pro-vision
    litellm_params:
      model: gemini/gemini-pro-vision
      api_key: os.environ/GEMINI_API_KEY

  - model_name: gemini-pro-vision
    litellm_params:
      model: gemini/gemini-pro-vision
      api_key: os.environ/GEMINI_API_KEY_FALLBACK
