openapi: 3.1.3
info:
  title: GridoAI
  version: '1.0'
paths:
  /search:
    get:
      description: Search for documents in the knowledge base
      operationId: Search
      parameters:
      - name: query
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'
        '400':
          description: 'Invalid value for: query parameter query'
          content:
            text/plain:
              schema:
                type: string
        default:
          description: ''
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    Document:
      required:
      - uid
      - name
      - content
      - url
      - numberOfWords
      type: object
      properties:
        uid:
          type: string
          format: uuid
        name:
          type: string
        content:
          type: string
        url:
          type: string
        numberOfWords:
          type: integer
          format: int32
