name: Scala CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: "17" # for a specific JDK 17; or '17' for the latest JDK 17
          distribution: "graalvm" # New 'distribution' option
          cache: "sbt"
          components: native-image
      - name: Generate .jar
        run: sbt assembly
      - name: Save jar
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: target/scala-3.3.0/API-assembly-0.1.0-SNAPSHOT.jar
      - name: Build native image
        run: sbt graalvm-native-image:packageBin
      - name: Save native image
        uses: actions/upload-artifact@v2
        with:
          name: native-image
          path: target/graalvm-native-image/API
      - name: Run tests
        run: sbt test
        # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
      - name: Upload dependency graph
        uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
